$c.colors['seraphim'] = [
    '*':[
        background:'white',
        foreground:'black',
        caretColor:'#888888ff'
    ],
    '*.prompt':[
        background:'#ccccccFF',
        foreground:'black',
    ],
    '*.input':[
        background:'#ddddddFF',
        foreground:'black',
        caretColor:'#888888ff'
    ],
    '*.choice':[
        background:'#664544FF',
        foreground:'yellow'
    ]
]
